#pragma once

#include "NativeGameplayTags.h"

namespace BossArenaTags
{
	// SetByCaller magnitudes
	BOSSARENA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Data_Damage);
	BOSSARENA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Data_Cooldown);
	BOSSARENA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Data_Rage);

	// Owned state tags
	BOSSARENA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Invulnerable);
	BOSSARENA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Dodging);
	BOSSARENA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Blocking);
	BOSSARENA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Dead);
	BOSSARENA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Casting);
	BOSSARENA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Leaping);

	// Damage flags (asset tags on the damage spec)
	BOSSARENA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Damage_Unblockable);

	// Gameplay events
	BOSSARENA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Interrupt);

	// Warrior abilities
	BOSSARENA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Warrior_Attack);
	BOSSARENA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Warrior_Cleave);
	BOSSARENA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Warrior_Whirlwind);
	BOSSARENA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Warrior_LeapSlam);
	BOSSARENA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Warrior_Shockwave);
	BOSSARENA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Warrior_GroundRend);
	BOSSARENA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Warrior_Taunt);
	BOSSARENA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Warrior_Execute);
	BOSSARENA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Warrior_Dodge);
	BOSSARENA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Warrior_Block);

	// Warrior cooldowns
	BOSSARENA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cooldown_Warrior_Whirlwind);
	BOSSARENA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cooldown_Warrior_LeapSlam);
	BOSSARENA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cooldown_Warrior_Shockwave);
	BOSSARENA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cooldown_Warrior_GroundRend);
	BOSSARENA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cooldown_Warrior_Taunt);
	BOSSARENA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cooldown_Warrior_Execute);
	BOSSARENA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cooldown_Warrior_Dodge);

	// Boss / add abilities
	BOSSARENA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Boss);
	BOSSARENA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Boss_Transition);
	BOSSARENA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Boss_HardEnrage);
}
